package io.nuwe.DiscordBotQR.command;

import java.net.MalformedURLException;

import org.javacord.api.entity.message.MessageFlag;
import org.javacord.api.entity.message.embed.EmbedBuilder;
import org.javacord.api.entity.user.User;
import org.javacord.api.event.interaction.SlashCommandCreateEvent;
import org.javacord.api.interaction.SlashCommandInteraction;
import org.javacord.api.listener.interaction.SlashCommandCreateListener;

import io.nuwe.DiscordBotQR.utils.QrColors;
import io.nuwe.DiscordBotQR.utils.Validator;

public class QrCommandInteractor implements SlashCommandCreateListener {

	@Override
	public void onSlashCommandCreate(SlashCommandCreateEvent event) {
		if (event.getSlashCommandInteraction().getCommandName().equalsIgnoreCase("qr")) {
			
			SlashCommandInteraction interaction = event.getSlashCommandInteraction();
			
			try {
				
				//build the response
				EmbedBuilder embed = getResponse(interaction);
				
				//response
				interaction.createImmediateResponder()
				.addEmbed(embed)
				.respond();

				
			} catch (Exception e) {
				interaction.createImmediateResponder()
				.append("Something went wrong: " + e.getMessage())
				.setFlags(MessageFlag.EPHEMERAL)
				.respond();
			}
		}
	}

	private EmbedBuilder getResponse(SlashCommandInteraction interaction) throws MalformedURLException {

		String url = interaction.getFirstOptionStringValue().get();
		Validator.validateURL(url);
		
		String color = interaction.getSecondOptionStringValue().orElse("BLACK");
		String colorCode = QrColors.getCode(color);
		
		
		String description = interaction.getThirdOptionStringValue().orElse("Autogenerated QR.");
		User user = interaction.getUser();
		
		EmbedBuilder embed = new EmbedBuilder()
			    .setTitle("QR link")
			    .setDescription(description)
			    .setAuthor(user)
			    .addInlineField("Link", url)
			    //.setColor(QrColors.getRGBfromHexCode("303136"))
			    .setColor(QrColors.getRGBfromHexCode(colorCode))
			    .setImage("https://chart.googleapis.com/chart?cht=qr&chs=300x200&chld=L&chco=" + colorCode + "&chl=" + url);

		return embed;
	}


}
